- name: install nexus      
  hosts: nexus-ec2               
  become: true                         
  roles:
    - role: roles/nexus


- name: install PostgreSQL and sonarqube      
  hosts: sonarqube-ec2              
  become: true                         
  roles:
    - role: roles/PostgreSQL
    - role: roles/sonarqube